### ISSUE TITLE
generate sitemap from the CLI

### ISSUE THREAD

**Issue by tacman** [abdellahrk/SeoBundle#16]
To generate the URL from the sitemap console command, set the default_uri.

```yaml
# config/packages/routing.yaml
framework:
    router:
        # ...
        default_uri: 'https://example.org/my/path/'
```

https://symfony.com/doc/current/routing.html#generating-urls-in-commands
